-- MySQL Script generated by MySQL Workbench
-- Fri Sep 22 18:02:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema model_pizzeria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `model_pizzeria` ;

-- -----------------------------------------------------
-- Schema model_pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `model_pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `model_pizzeria` ;

-- -----------------------------------------------------
-- Table `model_pizzeria`.`adreces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `model_pizzeria`.`adreces` (
  `id` INT NOT NULL,
  `carrer` VARCHAR(45) NOT NULL,
  `num` VARCHAR(10) NOT NULL,
  `pis_porta` VARCHAR(10) NOT NULL,
  `codi_postal` VARCHAR(5) NOT NULL,
  `ciutat` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model_pizzeria`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `model_pizzeria`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `cognom_1` VARCHAR(45) NOT NULL,
  `cognom_2` VARCHAR(45) NOT NULL,
  `adreça_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clients_adreces1_idx` (`adreça_id` ASC) ,
  CONSTRAINT `adreça_id`
    FOREIGN KEY (`adreça_id`)
    REFERENCES `model_pizzeria`.`adreces` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model_pizzeria`.`botigues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `model_pizzeria`.`botigues` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `adreça_botiga_id` INT NOT NULL,
  INDEX `fk_botigues_adreces1_idx` (`adreça_botiga_id` ASC) ,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `adreça_botiga_id_UNIQUE` (`adreça_botiga_id` ASC) ,
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) ,
  CONSTRAINT `adreça_botiga_id`
    FOREIGN KEY (`adreça_botiga_id`)
    REFERENCES `model_pizzeria`.`adreces` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model_pizzeria`.`empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `model_pizzeria`.`empleats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `cognom_1` VARCHAR(45) NOT NULL,
  `cognom_2` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(8) NOT NULL,
  `nif` VARCHAR(9) NOT NULL,
  `carrec` ENUM('CUINER', 'REPARTIDOR') NOT NULL,
  `botiga_empleat_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `botigaActual_idx` (`botiga_empleat_id` ASC) ,
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) ,
  CONSTRAINT `botiga_empleat_id`
    FOREIGN KEY (`botiga_empleat_id`)
    REFERENCES `model_pizzeria`.`botigues` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model_pizzeria`.`lliuraments_domicili`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `model_pizzeria`.`lliuraments_domicili` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_hora` DATETIME NULL,
  `empleat_id` INT NOT NULL,
  INDEX `fk_lliuraments_comandes_domicili_empleats1_idx` (`empleat_id` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `empleat_id`
    FOREIGN KEY (`empleat_id`)
    REFERENCES `model_pizzeria`.`empleats` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model_pizzeria`.`comandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `model_pizzeria`.`comandes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `botiga_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `data_hora_comanda` DATETIME NOT NULL,
  `preu_total` FLOAT NOT NULL,
  `tipus_comanda` ENUM('BOTIGA', 'DOMICILI') NOT NULL,
  `lliurament_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `client_idx` (`client_id` ASC) ,
  INDEX `botiga_idx` (`botiga_id` ASC) ,
  INDEX `lliurament_id_idx` (`lliurament_id` ASC) ,
  CONSTRAINT `client_id`
    FOREIGN KEY (`client_id`)
    REFERENCES `model_pizzeria`.`clients` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `botiga_id`
    FOREIGN KEY (`botiga_id`)
    REFERENCES `model_pizzeria`.`botigues` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `lliurament_id`
    FOREIGN KEY (`lliurament_id`)
    REFERENCES `model_pizzeria`.`lliuraments_domicili` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model_pizzeria`.`categories_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `model_pizzeria`.`categories_pizza` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model_pizzeria`.`productes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `model_pizzeria`.`productes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `descripcio` VARCHAR(90) NOT NULL,
  `imatge` VARCHAR(45) NOT NULL,
  `preu` FLOAT NOT NULL,
  `tipus` ENUM('PIZZA', 'HAMBURGUESA', 'BEGUDA') NOT NULL,
  `cat_pizza` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `cat_piz_idx` (`cat_pizza` ASC) ,
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) ,
  CONSTRAINT `cat_pizza`
    FOREIGN KEY (`cat_pizza`)
    REFERENCES `model_pizzeria`.`categories_pizza` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model_pizzeria`.`linies_comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `model_pizzeria`.`linies_comanda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comanda_id` INT NOT NULL,
  `producte_id` INT NOT NULL,
  `unitats` INT NOT NULL,
  `preu_linia` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `prodCom_idx` (`producte_id` ASC) ,
  INDEX `numComandaBotiga_idx` (`comanda_id` ASC) ,
  CONSTRAINT `producte_id`
    FOREIGN KEY (`producte_id`)
    REFERENCES `model_pizzeria`.`productes` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `comanda_id`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `model_pizzeria`.`comandes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
