-- MySQL Script generated by MySQL Workbench
-- Sun May 14 19:59:26 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`adreces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`adreces` (
  `adreces_id` INT NOT NULL AUTO_INCREMENT,
  `carrer` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `pis` VARCHAR(45) NOT NULL,
  `porta` VARCHAR(45) NOT NULL,
  `codi_postal` VARCHAR(5) NOT NULL,
  `ciutat` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`adreces_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`clients` (
  `clients_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `cognom1` VARCHAR(45) NOT NULL,
  `cognom2` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(8) NOT NULL,
  `adreça` INT NOT NULL,
  PRIMARY KEY (`clients_id`),
  INDEX `adreça_idx` (`adreça` ASC),
  CONSTRAINT `adreça`
    FOREIGN KEY (`adreça`)
    REFERENCES `pizzeria`.`adreces` (`adreces_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`botigues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`botigues` (
  `botigues_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(8) NOT NULL,
  `adreçaBotiga` INT NOT NULL,
  PRIMARY KEY (`botigues_id`),
  UNIQUE INDEX `adreçaBotiga_UNIQUE` (`adreçaBotiga` ASC),
  CONSTRAINT `adreçaBotiga`
    FOREIGN KEY (`adreçaBotiga`)
    REFERENCES `pizzeria`.`adreces` (`adreces_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`empleats` (
  `empleats_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `cognom1` VARCHAR(45) NOT NULL,
  `cognom2` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(8) NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  `carrec` VARCHAR(45) NOT NULL,
  `botigaActual` INT NOT NULL,
  PRIMARY KEY (`empleats_id`),
  INDEX `botigaActual_idx` (`botigaActual` ASC),
  CONSTRAINT `botigaActual`
    FOREIGN KEY (`botigaActual`)
    REFERENCES `pizzeria`.`botigues` (`botigues_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`comandes_botiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`comandes_botiga` (
  `comandes_botiga_id` INT NOT NULL AUTO_INCREMENT,
  `botiga` INT NULL,
  `clientBot` INT NULL,
  `empleatAten` INT NOT NULL,
  `dataHora` DATETIME NOT NULL,
  `preuTotal` FLOAT NULL,
  PRIMARY KEY (`comandes_botiga_id`),
  INDEX `client_idx` (`clientBot` ASC),
  INDEX `atenComanda_idx` (`empleatAten` ASC),
  INDEX `botiga_idx` (`botiga` ASC),
  CONSTRAINT `clientBot`
    FOREIGN KEY (`clientBot`)
    REFERENCES `pizzeria`.`clients` (`clients_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `empleatAten`
    FOREIGN KEY (`empleatAten`)
    REFERENCES `pizzeria`.`empleats` (`empleats_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `botiga`
    FOREIGN KEY (`botiga`)
    REFERENCES `pizzeria`.`botigues` (`botigues_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`comandes_domicili`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`comandes_domicili` (
  `comandes_domicili_id` INT NOT NULL AUTO_INCREMENT,
  `botigaDom` INT NOT NULL,
  `clientDom` INT NOT NULL,
  `atenEmpleat` INT NOT NULL,
  `repartidor` INT NOT NULL,
  `dataHoraComanda` DATETIME NOT NULL,
  `dataHoraEntrega` DATETIME NULL,
  `preuTotal` FLOAT NULL,
  PRIMARY KEY (`comandes_domicili_id`),
  INDEX `botigaDom_idx` (`botigaDom` ASC),
  INDEX `clientDom_idx` (`clientDom` ASC),
  INDEX `atenComDom_idx` (`atenEmpleat` ASC),
  INDEX `repartidor_idx` (`repartidor` ASC),
  CONSTRAINT `botigaDom`
    FOREIGN KEY (`botigaDom`)
    REFERENCES `pizzeria`.`botigues` (`botigues_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `clientDom`
    FOREIGN KEY (`clientDom`)
    REFERENCES `pizzeria`.`clients` (`clients_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `atenEmpleat`
    FOREIGN KEY (`atenEmpleat`)
    REFERENCES `pizzeria`.`empleats` (`empleats_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `repartidor`
    FOREIGN KEY (`repartidor`)
    REFERENCES `pizzeria`.`empleats` (`empleats_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`categoriesPizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`categoriesPizza` (
  `categoriesPizza_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `descripcio` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`categoriesPizza_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`productes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`productes` (
  `productes_id` INT NOT NULL AUTO_INCREMENT,
  `tipus` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `descripcio` VARCHAR(90) NOT NULL,
  `imatge` LONGBLOB NOT NULL,
  `preu` FLOAT NOT NULL,
  `cat_pizza` INT NULL,
  PRIMARY KEY (`productes_id`),
  INDEX `cat_piz_idx` (`cat_pizza` ASC),
  CONSTRAINT `cat_piz`
    FOREIGN KEY (`cat_pizza`)
    REFERENCES `pizzeria`.`categoriesPizza` (`categoriesPizza_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`linies_comandes_botiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`linies_comandes_botiga` (
  `linies_comandes_botiga_id` INT NOT NULL AUTO_INCREMENT,
  `numComanda` INT NOT NULL,
  `prodComanda` INT NOT NULL,
  `unitatsProd` INT NOT NULL,
  `preu_linia` FLOAT NOT NULL,
  PRIMARY KEY (`linies_comandes_botiga_id`),
  INDEX `prodCom_idx` (`prodComanda` ASC),
  INDEX `numComandaBotiga_idx` (`numComanda` ASC),
  CONSTRAINT `prodComanda`
    FOREIGN KEY (`prodComanda`)
    REFERENCES `pizzeria`.`productes` (`productes_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `numComanda`
    FOREIGN KEY (`numComanda`)
    REFERENCES `pizzeria`.`comandes_botiga` (`comandes_botiga_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`linies_comandes_domicili`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`linies_comandes_domicili` (
  `linies_comandes_domicili_id` INT NOT NULL AUTO_INCREMENT,
  `numComDom` INT NOT NULL,
  `prodComDom` INT NOT NULL,
  `unitats` INT NOT NULL,
  `preuLinia` FLOAT NOT NULL,
  PRIMARY KEY (`linies_comandes_domicili_id`),
  INDEX `numComandaDom_idx` (`numComDom` ASC),
  INDEX `producte_idx` (`prodComDom` ASC),
  CONSTRAINT `numComDom`
    FOREIGN KEY (`numComDom`)
    REFERENCES `pizzeria`.`comandes_domicili` (`comandes_domicili_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `prodComDom`
    FOREIGN KEY (`prodComDom`)
    REFERENCES `pizzeria`.`productes` (`productes_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
